# Generated by Django 4.2.3 on 2023-09-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_bookshopemodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshopemodel',
            name='category',
            field=models.CharField(choices=[('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Sci-Fi'), ('Humor', 'Humor'), ('Horror', 'Horror'), ('Biography', 'Biography'), ('Fantasi', 'Fantasi'), ('Historical Fiction', 'Historical Fiction')], max_length=30),
        ),
    ]
