# Generated by Django 4.2.3 on 2023-09-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_bookshopemodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshopemodel',
            name='book_name',
            field=models.CharField(max_length=50),
        ),
    ]
