# Generated by Django 4.2.3 on 2023-09-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_searchmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchModel',
        ),
    ]
